[callcenter-inbound]
; Quando o ramal 1001 disca "1002", chama o ramal 1002.
; É essa chamada que vai gerar os eventos que seu Node vai capturar via AMI.
exten => 1002,1,NoOp(Chamada de ${CALLERID(num)} para 1002 - simulando cliente ligando pro atendente)
 same => n,Dial(PJSIP/1002,30)
 same => n,Hangup()

exten => 1001,1,NoOp(Chamada de ${CALLERID(num)} para 1001)
 same => n,Dial(PJSIP/1001,30)
 same => n,Hangup()
