[global]
type=global
max_forwards=70

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; ==========================================
; RAMAL 1001 - use como "cliente" simulado
; ==========================================
[1001]
type=endpoint
context=callcenter-inbound
disallow=all
allow=ulaw
allow=alaw
auth=1001-auth
aors=1001-aor

[1001-auth]
type=auth
auth_type=userpass
password=senha1001
username=1001

[1001-aor]
type=aor
max_contacts=1

; ==========================================
; RAMAL 1002 - use como "atendente" simulado
; ==========================================
[1002]
type=endpoint
context=callcenter-inbound
disallow=all
allow=ulaw
allow=alaw
auth=1002-auth
aors=1002-aor

[1002-auth]
type=auth
auth_type=userpass
password=senha1002
username=1002

[1002-aor]
type=aor
max_contacts=1
